### ISSUE TITLE
Replace “aliases” with plugins

### ISSUE THREAD

**Issue by HalosGhost** [HalosGhost/irc_bot#13]
Aliases have significant creep, are all kept in one file which makes them very difficult to approach and have a lot of boiler-plate.

A plugin system (the start of which just got implemented) allows us to separate out the code into namespaced modules (which means better organization and approachability) and to extract some of the boiler-plate so that it doesn't need to be repeated in every module.

Now that the basic plugin system has been implemented, each alias should be migrated to to a plugin:

1. [x] `fact` (`count`, `search`, `'<key>' is '<value>'` and `'<key>' is nothing`)
2. [x] `convert` (along with `units`)
3. [x] `configure` (`get`, `type`, `set`)
4. [x] `quote` (`grab`, `opt-in`, `opt-out`, `status`, `random`, `<nick>`, `search`, `delete`)

**Comment by meskarune** [comment]
Is there an updated list for these?

**Comment by HalosGhost** [comment]
The only thing left which is readily migrateable to a plugin is `convert`.

**Comment by meskarune** [comment]
Convert is done \o/

All that is left is whatever little things are in irc_aliases.lua, rot13, picks and such.

**Comment by HalosGhost** [comment]
solid!
