### ISSUE TITLE
Macro system

### ISSUE THREAD

**Issue by HalosGhost** [HalosGhost/irc_bot#14]
The new plugin system migration is going well, a few quirks to work out here and there, but overall good.

However, there is a bit of a usability issue with plugins; namely, they're a bit verbose. Macros are a proposal to allow for admins to be able to define shortcuts that the bot will recognize, replace and then continue normal parsing.

Macros have a key much like the current keys that aliases have (basic lua patterns), and values that are just strings. It could be thought of as being similar to CPP-style object-like macros with the exception that the token to trigger the replacement can be a pattern rather than just a plain identifier.

So, we could define the following macro:

```lua
['^aw$'] = 'mediawiki https://wiki.archlinux.org/api.php'
```
A user could then type `<botname>: aw <query>` to search the ArchWiki for `<query>` rather than needing to type out the full command.

In addition to these nice features, this mapping (unlike aliases) can be trivially stored in the database which allows for easy runtime definition.

Below is a list of aliases that will not find a home in a plugin, but can easily be implemented as a macro (e.g., on top of `eval`):

- [x] `pick`
- [x] `archwiki` and `wiki`
- [x] `judges`
- [x] `rot13`
- [x] `bloat`
- [x] `roll`
- [x] `test`
- [x] `you`
- [x] `is`
- [ ] `give`
- [x] `ug*`
- [x] URL title announcements

**Comment by meskarune** [comment]
I think the only things left is say, act, you, give, and bloat
