### ISSUE TITLE
Unit conversion plugin

### ISSUE THREAD

**Issue by achilleas-k** [HalosGhost/irc_bot#4]
A Wolfram Alpha plugin would do all kinds of conversions and answer useful queries.

**Comment by HalosGhost** [comment]
I have gotten an API key for WA which is limited to 2000 calls per month. I will start work on implementing a plugin for this Soon™.

**Comment by HalosGhost** [comment]
Though Wolfram|Alpha has been abandoned and removed, we have a very flexible unit conversion plugin built-in now. :D
